# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'WTFSwiftUI'
project 'WTFSwiftUI.project'
project '../DesignSystem/DesignSystem/DesignSystem.project'




target 'WTFSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WTFSwiftUI

end
